Version 4.13

// General
#include "Zscript/PBX/PBXWeapons_Spawners.zs"
#include "Zscript/PBX/PBXWeapons_Systems.zs"
#include "Zscript/PBX/PBXWeapons_Hud.zs"
#include "Zscript/PBX/PBXWeapons_Tips.zs"

// Big thanks to EmeraldCoastt and the BDP team for this
#include "Zscript/Maths/Include.zsc"

// Slot 1


// Slot 2
// Lever Action 
#include "Zscript/PBX_Weapons/Slot-2/Prosurv_LeverAction/Prosurv_LeverAction.zs"
#include "Zscript/PBX_Weapons/Slot-2/Prosurv_LeverAction/LeverAction_Wheel.zs"
#include "Zscript/PBX_Weapons/Slot-2/Prosurv_LeverAction/LeverAction_helpers.zs"

// Slot 3
// CSSG
#include "Zscript/PBX_Weapons/Slot-3/CSSG/CSSG.zs"
#include "Zscript/PBX_Weapons/Slot-3/CSSG/CSSG_Functions.zs"
#include "Zscript/PBX_Weapons/Slot-3/CSSG/CSSG_Casings.zs"
#include "Zscript/PBX_Weapons/Slot-3/CSSG/CSSG_Shells.zs"
#include "Zscript/PBX_Weapons/Slot-3/CSSG/CSSG_Upgrades.zs"
#include "Zscript/PBX_Weapons/Slot-3/CSSG/CSSG_Wheel.zs"
#include "Zscript/PBX_Weapons/Slot-3/CSSG/CSSG_Projectiles.zs"

// Slot 4
// Battle Rifle
#include "Zscript/PBX_Weapons/Slot-4/BattleRifle/BattleRifle.zs"
#include "Zscript/PBX_Weapons/Slot-4/BattleRifle/BattleRifle_Wheel.zs"
#include "Zscript/PBX_Weapons/Slot-4/BattleRifle/BattleRifle_helpers.zs"
// Metal Sniper
#include "Zscript/PBX_Weapons/Slot-4/MetalSniper/MetalSniper.zs"
#include "Zscript/PBX_Weapons/Slot-4/MetalSniper/MetalSniper_Wheel.zs"
#include "Zscript/PBX_Weapons/Slot-4/MetalSniper/MetalSniper_helpers.zs"


// Slot 5
// NeoHMG
#include "Zscript/PBX_Weapons/Slot-5/NeoHMG/NeoHMG.zs"
#include "Zscript/PBX_Weapons/Slot-5/NeoHMG/NeoHMG_Wheel.zs"
#include "Zscript/PBX_Weapons/Slot-5/NeoHMG/NeoHMG_helpers.zs"

// Slot 6
// Excavator
#include "Zscript/PBX_Weapons/Slot-6/Excavator/Excavator.zs"
#include "Zscript/PBX_Weapons/Slot-6/Excavator/Excavator_wheel.zs"
#include "Zscript/PBX_Weapons/Slot-6/Excavator/Excavator_Helpers.zs"
// Cyberdemon RL
#include "Zscript/PBX_Weapons/Slot-6/CyberdemonRL/CyberdemonRL.zs"
#include "Zscript/PBX_Weapons/Slot-6/CyberdemonRL/CyberRL_helpers.zs"
// Mastermind CG
#include "Zscript/PBX_Weapons/Slot-6/MastermindCG/MastermindCG.zs"
#include "Zscript/PBX_Weapons/Slot-6/MastermindCG/MastermindCG_helpers.zs"

// Slot 7

// Slot 8

// Slot 9
// Demon Ext
#include "Zscript/PBX_Weapons/Slot-9/DemonicExterminator/DemonicExt.zs"
#include "Zscript/PBX_Weapons/Slot-9/DemonicExterminator/DemonicExtFunctions.zs"
#include "Zscript/PBX_Weapons/Slot-9/DemonicExterminator/DemonicExtAttacks.zs"
#include "Zscript/PBX_Weapons/Slot-9/DemonicExterminator/DemonicExtProj.zs"
#include "Zscript/PBX_Weapons/Slot-9/DemonicExterminator/DemonicExtProj2.zs"
#include "Zscript/PBX_Weapons/Slot-9/DemonicExterminator/DemonicExtProj3.zs"
#include "Zscript/PBX_Weapons/Slot-9/DemonicExterminator/DemonicExtStuff.zs"
#include "Zscript/PBX_Weapons/Slot-9/DemonicExterminator/DemonicExt_Wheel.zs"


